### ISSUE TITLE
Liquibase codegen plugin doesn't understand paths or JSONB column types

### ISSUE THREAD

**Issue by kenyee** [jOOQ/jOOQ#11814]
### Expected behavior
Codegen plugin should work w/ liquibase changelogs in YAML format.

### Actual behavior
It can't find the JSONB data type or the files.
Error is:
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.14.9:generate (generate-h2) on project apiservice: Error running jOOQ code generation tool: Error while exporting schema: Error parsing src/main/resources/db/changelog/changelog-master.yaml: db/changelog/create-initial-tables-changelog-1.yaml does not exist -> [Help 1]

### Steps to reproduce the problem
I have this in my application-local.yaml:
```
spring.liquibase.change-log: classpath:/db/changelog/changelog-master.yaml
logging.level.liquibase: INFO
spring.datasource.driver-class-name: org.h2.Driver
spring.datasource.url: jdbc:h2:mem:testdb;INIT=create domain if not exists jsonb as text;MODE=PostgreSQL
spring.datasource.username: sa
spring.datasource.password: sa
spring.h2.console.enabled: true
```

in src/main/resources/db/changelog/changelog-master.yaml:
```
databaseChangeLog:
  - include:
      file: db/changelog/create-initial-tables-changelog-1.yaml
  - include:
      file: db/changelog/insert-initial-data-changelog-2.sql
```

The first changelog looks like this:
```
databaseChangeLog:
  - changeSet:
      id: create-initial-tables
      author: kyee
      preConditions:
        - onFail: MARK_RAN
          not:
            tableExists:
              tableName: Admin
      changes:
        - createTable:
            tableName: Admin
            columns:
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: admin_pkey
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: super_admin
                  type: BOOLEAN
                  constraints:
                    nullable: false
        - createIndex:
            tableName: Admin
            columns:
              - column:
                  name: email
              - column:
                  name: super_admin
            indexName: index_super_admin
        - createTable:
            tableName: Repo
            columns:
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: repo_pkey
              - column:
                  name: description
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: git_base_url
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: config_data
                  type: JSONB
                  constraints:
                    nullable: false
        - createTable:
            tableName: Admin_Repo
            columns:
              - column:
                  name: admin_email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: repo_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
        - createIndex:
            tableName: Admin_Repo
            columns:
              - column:
                  name: admin_email
              - column:
                  name: repo_name
            indexName: index_admin_repo
        - createTable:
            tableName: AccessKey
            columns:
              - column:
                  name: id
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: accesskey_pkey
              - column:
                  name: repo_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: VARCHAR(255)
              - column:
                  name: hashed_key
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: permissions
                  type: VARCHAR
                  constraints:
                    nullable: false
        - createIndex:
            tableName: AccessKey
            columns:
              - column:
                  name: repo_name
              - column:
                  name: hashed_key
            indexName: index_accesskey
      rollback:
        - dropTable:
            tableName: Admin_Repo
        - dropTable:
            tableName: Admin
        - dropTable:
            tableName: Repo
        - dropTable:
            tableName: AccessKey
```

Second changelog is can be filled w/ anything...it can't find the first one.

### Versions

- jOOQ: 3.14.9
- Java: 11
- Database (include vendor): H2 (for unit tests) and Postgres (deployment)
- OS: OSX
- JDBC Driver (include name if inofficial driver): Spring Boot JDBC 2.4.3
