### ISSUE TITLE
codegen-liquibase : scripts relative to classpath

### ISSUE THREAD

**Issue by lolo101** [jOOQ/jOOQ#12298]
Hi !

I have an issue with jOOQ code generation from liquibase scripts and I cannot figure a way out, and I failed to find help on the web.

I configured Maven plugin as such : 
```
	<plugin>
		<groupId>org.jooq</groupId>
		<artifactId>jooq-codegen-maven</artifactId>
		<dependencies>
			...
		</dependencies>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<generator>
				<database>
					<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
					<properties>
						<property>
							<key>scripts</key>
							<value>src/main/resources/db/changelog/db.changelog-master.yaml</value>
						</property>
					</properties>
				</database>
			</generator>
		</configuration>
	</plugin>
```
And my `db.changelog-master.yaml` includes other scripts relative to the classpath : 
```
databaseChangeLog:
  - include:
      file: classpath:db/changelog/001.db-init.yaml
  - include:
      file: classpath:...
```
However the plugin cannot use the project output classpath (or I dont know how to).
And I cannot build the project without executing the jOOQ code generation because it relies on generated classes.

I find myself locked.

Can you help me about this issue ?

**Comment by lolo101** [comment]
Actually the only way I found to workaround my issue is by specifying included scripts relative to changelog file : 
```
databaseChangeLog:
  - include:
      file: 001.db-init.yaml
      relativeToChangelogFile: true
  - include:
      file: 002...
      relativeToChangelogFile: true
```
But I dont find this solution very satisfying. What do you think ?
