### ISSUE TITLE
Code generation not working for Liquibase YAML file 

### ISSUE THREAD

**Issue by myatmin** [jOOQ/jOOQ#14156]
### Expected behavior

Codes should be generated like when using with XML file.
Sample XML file as below, adapted from [Liquibase](https://docs.liquibase.com/concepts/changelogs/xml-format.html)

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:pro="http://www.liquibase.org/xml/ns/pro"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
                        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
                        http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">

    <changeSet id="1" author="nvoxland">
        <createTable tableName="person">
            <column name="id" type="int" autoIncrement="true">
                <constraints primaryKey="true" nullable="false" />
            </column>
            <column name="firstname" type="varchar(50)" />
            <column name="lastname" type="varchar(50)">
                <constraints nullable="false" />
            </column>
            <column name="state" type="char(2)" />
        </createTable>
    </changeSet>

    <changeSet id="2" author="nvoxland">
        <addColumn tableName="person">
            <column name="username" type="varchar(8)" />
        </addColumn>
    </changeSet>
    <changeSet id="3" author="nvoxland">
        <addLookupTable
            existingTableName="person" existingColumnName="state"
            newTableName="state" newColumnName="id" newColumnDataType="char(2)" />
    </changeSet>

</databaseChangeLog>
```

### Actual behavior

No code were generated.
Sample file as below, adapted from [Liquibase](https://docs.liquibase.com/concepts/changelogs/yaml-format.html)

```yml
databaseChangeLog:
  - changeSet:
      id: 1
      author: nvoxland
      changes:
        - createTable:
            tableName: person
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: firstname
                  type: varchar(50)
              - column:
                  name: lastname
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: state
                  type: char(2)

  - changeSet:
      id: 2
      author: nvoxland
      changes:
        - addColumn:
            tableName: person
            columns:
              - column:
                  name: username
                  type: varchar(8)

  - changeSet:
      id: 3
      author: nvoxland
      changes:
        - addLookupTable:
            existingTableName: person
            existingColumnName: state
            newTableName: state
            newColumnName: id
            newColumnDataType: char(2)

```

### Steps to reproduce the problem

Configuration as below

```xml
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.17.4</version>
                <executions>
                    <execution>
                        <?m2e execute onConfiguration?>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <generator>
                        <database>
                            <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                            <includes>.*</includes>
                            <properties>
                                <property>
                                    <key>rootPath</key>
                                    <value>${project.basedir}/src/main/resources/liquibase/changelog</value>
                                </property>
                                <property>
                                    <key>scripts</key>
                                    <value>db.yaml</value>
                                </property>
                            </properties>
                        </database>
                        <generate />
                        <target>
                            <packageName>com.foo.bar</packageName>
                            <directory>${project.build.directory}/generated-sources/jooq</directory>
                        </target>
                    </generator>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jooq</groupId>
                        <artifactId>jooq-meta-extensions-liquibase</artifactId>
                        <version>3.17.4</version>
                    </dependency>
                </dependencies>
            </plugin>
```

### jOOQ Version

3.17.4

### Database product and version

PostgreSQL

### Java Version

17

### OS Version

Debian Bullseye

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.6
