### ISSUE TITLE
Manual TOC should visually distinguish between immediate subsections and their nested subsections

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#18072]
This is an example TOC in the manual, as found here:
https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/

![Image](https://github.com/user-attachments/assets/537c72e5-dc4f-4ef3-a72b-8f12836931df)

It is not immediately clear which ones are table expressions (top level), and which sections are their respective nested subsections.

This is relatively simple, if we put a class `.x` on every immediate subsection of a TOC:

![Image](https://github.com/user-attachments/assets/b24c4df8-15b7-40d9-aa0d-c45fabcfb5c5)

It just needs:

```css
*:not(.x) + * + .x {
    margin-top: 0.5em
}

.x:not(:has(+ * + .x)) {
    margin-bottom: 0.5em
}

dd {
    padding-left: 1em;
}

dd.x {
    font-weight: bold;
    padding-left: 0.5em;
}
```
